expected_output =  {
   'power_module':{
      '0/PM0':{
         'input_volts':'118.0',
         'input_amps':'1.1',
         'output_volts':'12.0',
         'output_amps':'7.7',
         'supply_type':'PSU2KW-ACPI',
         'status':'OK'
      },
      '0/PM1':{
         'input_volts':'117.5',
         'input_amps':'0.8',
         'output_volts':'12.1',
         'output_amps':'4.2',
         'supply_type':'PSU2KW-ACPI',
         'status':'OK'
      }
   }
}
