expected_output= {
    "plane_id":{
        "0":{
            "admin_state":"01",
            "plane_state":"01",
            "ud_counter":"08",
            "mcast_counter":"00"
        },
        "1":{
            "admin_state":"01",
            "plane_state":"01",
            "ud_counter":"08",
            "mcast_counter":"00"
        },
        "2":{
            "admin_state":"01",
            "plane_state":"01",
            "ud_counter":"08",
            "mcast_counter":"00"
        },
        "3":{
            "admin_state":"01",
            "plane_state":"01",
            "ud_counter":"08",
            "mcast_counter":"00"
        },
        "4":{
            "admin_state":"01",
            "plane_state":"01",
            "ud_counter":"08",
            "mcast_counter":"00"
        }
    }
}
